# GitHub Sponsors & Funding options for FindingExcellence PRO
# Built by Ayesa - Finding Excellence in intelligent file search

github: [jrodeiro5]
# patreon: # Add if Ayesa has Patreon
# ko_fi: # Add if Ayesa has Ko-fi
# custom: ['https://www.ayesa.com/sponsor']  # Uncomment for custom donation link
